---
- name: Configure EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present
    
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    
    - name: Pull Docker image from ECR
      docker_image:
        name: "{{ docker_image }}"
        source: pull

    - name: Run the application container
      docker_container:
        name: animal-click-app
        image: "{{ docker_image }}"
        state: started
        ports:
          - "80:80"